In [2]:
from tensorflow.keras.preprocessing.text import one_hot

c:\Users\ptani\OneDrive\Desktop\python\venv\Lib\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/attr_value.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
c:\Users\ptani\OneDrive\Desktop\python\venv\Lib\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/tensor.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
c:\Users\ptani\OneDrive\Desktop\python\venv\Lib\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/resource_handle.proto. Please 

In [4]:
sent=['the glass of milk','the glass of juice','the cup of tea','I am going to the market','iam a good boy','iam a good developer','understand the meaning of words','your videos are good','i love to watch your videos']

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am going to the market',
 'iam a good boy',
 'iam a good developer',
 'understand the meaning of words',
 'your videos are good',
 'i love to watch your videos']

In [4]:
voc_size=10000

In [5]:
#one hot representation
onehot_repr=[one_hot(words,voc_size)for words in sent]
onehot_repr

[[2005, 4749, 9404, 8595],
 [2005, 4749, 9404, 6302],
 [2005, 7306, 9404, 1582],
 [9015, 5965, 3975, 6821, 2005, 4299],
 [7577, 4455, 8771, 9751],
 [7577, 4455, 8771, 5313],
 [7976, 2005, 9911, 9404, 6420],
 [2928, 4421, 5258, 8771],
 [9015, 329, 6821, 5693, 2928, 4421]]

In [7]:
#word embedding 
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [ ]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length) ##pre-->>front padding and post-->>end padding
embedded_docs

array([[   0,    0,    0,    0, 2005, 4749, 9404, 8595],
       [   0,    0,    0,    0, 2005, 4749, 9404, 6302],
       [   0,    0,    0,    0, 2005, 7306, 9404, 1582],
       [   0,    0, 9015, 5965, 3975, 6821, 2005, 4299],
       [   0,    0,    0,    0, 7577, 4455, 8771, 9751],
       [   0,    0,    0,    0, 7577, 4455, 8771, 5313],
       [   0,    0,    0, 7976, 2005, 9911, 9404, 6420],
       [   0,    0,    0,    0, 2928, 4421, 5258, 8771],
       [   0,    0, 9015,  329, 6821, 5693, 2928, 4421]], dtype=int32)

In [10]:
#feature representation
dim=10 


In [13]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\ptani\OneDrive\Desktop\python\venv\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [14]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [15]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step


array([[[ 4.66339700e-02,  1.94268711e-02,  2.49896683e-02,
         -4.82468717e-02,  4.43427823e-02, -3.02091241e-02,
         -3.89324203e-02, -3.66986021e-02,  4.44479026e-02,
          4.08109091e-02],
        [ 4.66339700e-02,  1.94268711e-02,  2.49896683e-02,
         -4.82468717e-02,  4.43427823e-02, -3.02091241e-02,
         -3.89324203e-02, -3.66986021e-02,  4.44479026e-02,
          4.08109091e-02],
        [ 4.66339700e-02,  1.94268711e-02,  2.49896683e-02,
         -4.82468717e-02,  4.43427823e-02, -3.02091241e-02,
         -3.89324203e-02, -3.66986021e-02,  4.44479026e-02,
          4.08109091e-02],
        [ 4.66339700e-02,  1.94268711e-02,  2.49896683e-02,
         -4.82468717e-02,  4.43427823e-02, -3.02091241e-02,
         -3.89324203e-02, -3.66986021e-02,  4.44479026e-02,
          4.08109091e-02],
        [ 1.21835470e-02,  1.94662921e-02,  1.54850632e-03,
         -7.80713558e-03,  2.52801292e-02,  4.80546802e-03,
          3.80912088e-02,  4.17249314e-02, -1.030457

In [16]:
embedded_docs[0]

array([   0,    0,    0,    0, 2005, 4749, 9404, 8595], dtype=int32)

In [1]:
model.predict(embedded_docs[0].reshape(1,sent_length))

NameError: name 'model' is not defined